cache:
- "c:\\sr" # stack root, short paths == less problems

# to disable automatic builds
#build: off

environment:
  global:
    STACK_ROOT: "c:\\sr"

platform:
- x86
- x64

for:
- matrix:
    only:
      - platform: x86
  environment:
    STACK_YAML: "stack-windows-i386.yaml"
- matrix:
    only:
      - platform: x64
  environment:
    STACK_YAML: "stack.yaml"

install:
- if %PLATFORM%==x86 (curl -ostack.zip -L --insecure https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-windows-i386.zip) else (curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64)
- 7z x stack.zip stack.exe
- stack setup > nul

- curl -oCOIN-OR-1.8.0-win32-msvc12.zip -L --insecure https://www.coin-or.org/download/binary/OptimizationSuite/COIN-OR-1.8.0-win32-msvc12.zip
- 7z e COIN-OR-1.8.0-win32-msvc12.zip COIN-OR/win32-msvc12/bin/cbc.exe
- set PATH=%APPVEYOR_BUILD_FOLDER%;%PATH%

- curl -owinglpk-4.65.zip -L --insecure https://jaist.dl.sourceforge.net/project/winglpk/winglpk/GLPK-4.65/winglpk-4.65.zip
- 7z x winglpk-4.65.zip
- if %PLATFORM%==x86 set PATH=%APPVEYOR_BUILD_FOLDER%\glpk-4.65\w32;%PATH%
- if %PLATFORM%==x64 set PATH=%APPVEYOR_BUILD_FOLDER%\glpk-4.65\w64;%PATH%

build_script:
- git submodule init
- git submodule update

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test --bench --no-run-benchmarks --flag MIP:TestCBC --flag MIP:TestGlpsol
