on: [push, pull_request]
name: build
jobs:
  haskell-MIP:
    name: haskell-MIP
    runs-on: ${{ matrix.os }}
    env:
      STACK_YAML: ${{ matrix.stack_yaml }}
    strategy:
      matrix:
        include:
          - ghc: '8.8.4'
            os: ubuntu-latest
            stack_yaml: 'stack-ghc-8.8.yaml'
            coveralls: true
            flags: '--coverage --haddock --no-haddock-deps --flag MIP:TestCBC --flag MIP:TestGlpsol --flag MIP:TestLPSolve'
          - ghc: '8.8.4'
            os: macos-latest
            stack_yaml: 'stack-ghc-8.8.yaml'
            coveralls: false
            flags: '--flag MIP:TestCBC --flag MIP:TestGlpsol --flag MIP:TestLPSolve'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-haskell@v1.1.4
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
          stack-setup-ghc: true

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install coinor-cbc glpk-utils libglpk-dev lp-solve

      - name: Install packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cbc glpk
          curl -L https://jaist.dl.sourceforge.net/project/lpsolve/lpsolve/5.5.2.11/lp_solve_5.5.2.11_source.tar.gz | tar xz
          (cd lp_solve_5.5/lp_solve && sh ccc.osx)
          echo "${GITHUB_WORKSPACE}/lp_solve_5.5/lp_solve/bin/osx64" >> $GITHUB_PATH

      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build
        run: stack build --test --no-run-tests --bench --no-run-benchmarks ${{ matrix.flags }}

      - name: Test
        run: stack test ${{ matrix.flags }}

      - name: HPC Coveralls
        if: ${{ matrix.coveralls }}
        continue-on-error: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          curl -L https://github.com/lehins/stack-hpc-coveralls/releases/download/v0.0.6.0/shc.tar.gz | tar -xz
          ./shc --repo-token="$COVERALLS_REPO_TOKEN" combined all
